In [3]:
import numpy as np

In [157]:
a = [4,5,3,2,6,7,2]

In [158]:
for idx, x in enumerate(a):
    print(x)

4
5
3
2
6
7
2


In [16]:
for idx, x in enumerate(a):
    if x > 3:
        print(f"{x} in position {idx} is greater than 3")

4 in position 0 is greater than 3
5 in position 1 is greater than 3
6 in position 4 is greater than 3
7 in position 5 is greater than 3


In [19]:
l = []
for idx, x in enumerate(a):
    if x > 3:
        l.append((idx, x))

In [20]:
l

[(0, 4), (1, 5), (4, 6), (5, 7)]

In [30]:
# list comprehension
l = [x for _, x in enumerate(a) if x > 3]

In [34]:
a

[4, 5, 3, 2, 6, 7, 2]

In [36]:
a[2:4]

[3, 2]

In [40]:
a[-1]

2

In [41]:
a[-2:]

[7, 2]

In [44]:
a[::-1]

[2, 7, 6, 2, 3, 5, 4]

In [48]:
a

[4, 5, 3, 2, 6, 7, 2]

In [52]:
a[::-2]

[2, 6, 3, 4]

# Numpy

In [53]:
a

[4, 5, 3, 2, 6, 7, 2]

In [54]:
import numpy as np

In [57]:
b = np.array(a)

In [58]:
type(a), type(b)

(list, numpy.ndarray)

In [59]:
b.shape

(7,)

In [60]:
a = [[1,2,3], [6,7,8]]

In [62]:
b = np.array(a)

In [63]:
b

array([[1, 2, 3],
       [6, 7, 8]])

In [64]:
b.shape

(2, 3)

In [71]:
a = np.ones((4,4), dtype=int)

In [72]:
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [73]:
a.shape

(4, 4)

In [76]:
a = np.random.randint(0, 11, (6, 5))

In [77]:
a

array([[ 8, 10,  4,  6,  9],
       [ 1, 10,  3,  4,  0],
       [ 9,  3,  4,  0,  3],
       [ 1,  7,  9,  8,  0],
       [ 9,  9,  7,  3,  1],
       [ 9,  2,  0,  1,  0]])

In [81]:
a = np.random.rand(3,3)

In [82]:
a

array([[0.02787432, 0.49990458, 0.30427882],
       [0.02430947, 0.36808438, 0.21128853],
       [0.47720873, 0.50218778, 0.04288077]])

## Speed test

In [87]:
a = [2, 3, 4] * 5

In [85]:
a = [2 for _ in range(5)]

In [89]:
a = [i for i in range(1000)]

In [113]:
a = [2, 3, 4]
a * 5

[2, 3, 4, 2, 3, 4, 2, 3, 4, 2, 3, 4, 2, 3, 4]

In [114]:
a = np.array([2, 3, 4])
a * 5

array([10, 15, 20])

In [115]:
a = list(range(10000000))

In [104]:
%%timeit
b = [x * 20 for x in a]

371 ms ± 659 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [105]:
import numpy as np

In [116]:
a = np.array(a)

In [117]:
%%timeit 
b = a * 5

26.3 ms ± 39.6 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [119]:
%%timeit
reversed(a)

101 ns ± 0.444 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [120]:
%%timeit
a[::-1]

136 ns ± 0.366 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [135]:
a = np.random.randint(0, 10, (4,4))

In [136]:
a

array([[0, 7, 5, 1],
       [9, 0, 6, 9],
       [0, 3, 9, 0],
       [1, 9, 4, 7]])

In [137]:
a.sum(0)

array([10, 19, 24, 17])

In [138]:
a.sum(1)

array([13, 24, 12, 21])

In [139]:
a.sum()

70

## Pandas

In [121]:
import pandas as pd

In [124]:
a = np.random.rand(10, 6)

In [126]:
a.shape

(10, 6)

In [127]:
df = pd.DataFrame(a)

In [128]:
df

0         1         2         3         4         5
0  0.983854  0.437620  0.341101  0.491893  0.990857  0.606312
1  0.574704  0.181777  0.089316  0.778343  0.456097  0.488687
2  0.567876  0.591158  0.016551  0.429174  0.509247  0.417114
3  0.110002  0.396032  0.529920  0.208139  0.059961  0.469208
4  0.631527  0.273233  0.868240  0.357851  0.126179  0.731512
5  0.329367  0.383689  0.445752  0.626504  0.009287  0.990570
6  0.900670  0.045902  0.361319  0.023039  0.715184  0.202904
7  0.327283  0.154428  0.791380  0.976391  0.606592  0.962023
8  0.491427  0.355310  0.348896  0.565700  0.389605  0.589195
9  0.867533  0.418535  0.621320  0.432687  0.224813  0.668847

In [129]:
df[1] = "Data Science"

In [130]:
df

0             1         2         3         4         5
0  0.983854  Data Science  0.341101  0.491893  0.990857  0.606312
1  0.574704  Data Science  0.089316  0.778343  0.456097  0.488687
2  0.567876  Data Science  0.016551  0.429174  0.509247  0.417114
3  0.110002  Data Science  0.529920  0.208139  0.059961  0.469208
4  0.631527  Data Science  0.868240  0.357851  0.126179  0.731512
5  0.329367  Data Science  0.445752  0.626504  0.009287  0.990570
6  0.900670  Data Science  0.361319  0.023039  0.715184  0.202904
7  0.327283  Data Science  0.791380  0.976391  0.606592  0.962023
8  0.491427  Data Science  0.348896  0.565700  0.389605  0.589195
9  0.867533  Data Science  0.621320  0.432687  0.224813  0.668847

In [160]:
!ls

Intro.ipynb


In [161]:
!pwd

/home/alulab/Documentos/data-science
